services:
  web:
    build: .
    # El comando "sh -c ..." ejecuta los dos comandos en secuencia.
    # El primero es para recopilar los archivos estáticos en la ruta de STATIC_ROOT.
    # El segundo inicia el servidor Gunicorn.
    command: sh -c "python manage.py collectstatic --no-input && gunicorn formacion_demo.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      # Los volúmenes con nombres persisten los datos de staticfiles y media.
      - static_volume:/vol/web/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      db:
          condition: service_healthy
    container_name: django_app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      # Nginx accede a los mismos volúmenes nombrados para servir los archivos
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/vol/web/staticfiles
      - media_volume:/vol/web/media
    depends_on:
      - web
    container_name: nginx_proxy

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  static_volume:
  media_volume:
