"""
Django settings for formacion_demo project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, sys
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool) 

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'crispy_forms',
    'formacion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'formacion_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "formacion" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'formacion.context_processors.global_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'formacion_demo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Lógica para determinar el HOST de la base de datos
DB_HOST = config('DB_HOST_DOCKER', default=None)
if not DB_HOST:
    # Si DB_HOST_DOCKER no existe, asumimos que estamos en local.
    DB_HOST = config('DB_HOST_LOCAL', default='localhost')

# Configuración de la base de datos
DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE'),
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': DB_HOST,  # Aquí se usa la variable ya definida.
        'PORT': config('DB_PORT'),
    }
}

MEDIA_URL = '/media/'
MEDIA_ROOT = '/vol/web/media/'

# ============================================================================
# CONFIGURACIÓN DE AUTENTICACIÓN (Condicional basada en variable de entorno)
# ============================================================================

# Variable de entorno para controlar el uso de LDAP
USE_LDAP = config('LDAP', default=False, cast=bool)

if USE_LDAP:
    # Importaciones necesarias para LDAP
    import ldap
    from django_auth_ldap.config import LDAPSearch
    
    # Configuración de autenticación con LDAP
    AUTHENTICATION_BACKENDS = [
        'django_auth_ldap.backend.LDAPBackend',
        'django.contrib.auth.backends.ModelBackend',  # Backup para admin
    ]
    
    # Configuración de Conexión LDAP
    AUTH_LDAP_SERVER_URI = config('AUTH_LDAP_SERVER_URI')
    AUTH_LDAP_USER_DN_TEMPLATE = config('LDAP_BIND_DN')
    
    AUTH_LDAP_USER_ATTR_MAP = {
        "first_name": "givenName",
        "last_name": "sn",
        "email": "mail",
    }
    
    AUTH_LDAP_ALWAYS_UPDATE_USER = True
    
    # Opciones adicionales de seguridad (comentadas por defecto)
    # AUTH_LDAP_TLS_CACERTFILE = "/ruta/a/tu/proyecto/certs/ldap.crt"
    # AUTH_LDAP_TLS_VERIFY_SERVER_CERT = True
    
else:
    # Configuración de autenticación estándar de Django
    AUTHENTICATION_BACKENDS = [
        'django.contrib.auth.backends.ModelBackend',
    ]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
DEFAULT_CHARSET = 'utf-8'
TIME_ZONE = config('TIME_ZONE', default='Atlantic/Canary')
USE_I18N = True
USE_TZ = True
LANGUAGE_CODE = 'es-es'
USE_L10N = True

AUTH_USER_MODEL = 'formacion.Empleado'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = '/vol/web/staticfiles/'

# Sección de seguridad
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv())

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'formacion:dashboard'
LOGIN_URL = '/formacion/login/'
LOGOUT_REDIRECT_URL = 'formacion:login'

# --- Configuración del Servidor de Email ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True

# LOGGING
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
    },
    'root': {
        'level': 'INFO',
        'handlers': ['console'],
    },
    'loggers': {
        'formacion': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# --- NOMBRES DE GRUPOS DE USUARIO ---
GRUPO_EMPLEADO = 'Empleado'
GRUPO_COORDINADOR = 'Coordinador'
GRUPO_FORMACION = 'Formación'
GRUPO_RRHH = 'RRHH'
GRUPO_DIRECCION = 'Dirección'
GRUPO_ADMINISTRACION = 'Administración'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
