"""
Django settings for formacion_demo project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, sys
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool) 

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'crispy_forms',
    'formacion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'formacion_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "formacion" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'formacion.context_processors.global_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'formacion_demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Lógica para determinar el HOST de la base de datos
DB_HOST = config('DB_HOST_DOCKER', default=None)
if not DB_HOST:
    # Si DB_HOST_DOCKER no existe, asumimos que estamos en local.
    DB_HOST = config('DB_HOST_LOCAL', default='localhost')

# Configuración de la base de datos
DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE'),
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': DB_HOST,  # Aquí se usa la variable ya definida.
        'PORT': config('DB_PORT'),
    }
}

MEDIA_URL = '/media/'
MEDIA_ROOT = '/vol/web/media/'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

DEFAULT_CHARSET = 'utf-8'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
TIME_ZONE = config('TIME_ZONE')


LANGUAGE_CODE = 'es-es'

USE_L10N = True

AUTH_USER_MODEL = 'formacion.Empleado'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Directorio donde Django buscará archivos estáticos durante el desarrollo.
# Asegúrate de que esta ruta sea correcta para tu proyecto.
#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, 'formacion/static/'),
#]

# Directorio donde se recolectarán los archivos estáticos para producción.
STATIC_ROOT = '/vol/web/staticfiles/'

# Sección de seguridad
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'formacion:dashboard'
LOGIN_URL = '/formacion/login/'
LOGOUT_REDIRECT_URL = 'formacion:login'

# --- Configuración del Servidor de Email ---

# El backend de email que utilizará Django. 'smtp.EmailBackend' es el estándar.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# El servidor SMTP que vas a utilizar (ej. para Gmail)
EMAIL_HOST = config('EMAIL_HOST')

# El puerto del servidor SMTP
EMAIL_PORT = config('EMAIL_PORT')

# Tu dirección de correo electrónico que se usará para enviar los emails
EMAIL_HOST_USER = config('EMAIL_HOST_USER')

# Tu contraseña o, lo más recomendable, una "contraseña de aplicación" generada
# en la configuración de seguridad de tu cuenta de email.
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

# Utilizar TLS (Transport Layer Security) para la conexión
EMAIL_USE_TLS = True


# LOGGING
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # Define el formato que incluye la fecha, nivel, nombre y número de línea.
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s'
        },
    },
    'handlers': {
        # Configura el handler de consola para usar el formateador 'verbose'.
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
    },
    'root': {
        # El logger raíz usa el handler de consola por defecto.
        # Es el que atraparía los logs si 'propagate' estuviera en True.
        'level': 'INFO',
        'handlers': ['console'],
    },
    'loggers': {
        # Logger específico para la aplicación 'formacion'.
        'formacion': {
            'handlers': ['console'], # Usa el handler de consola.
            'level': 'INFO',
            'propagate': False, # ¡La clave para evitar la duplicación!
                               # Esto evita que los logs de 'formacion'
                               # se propaguen al logger raíz y se procesen de nuevo.
        },
    },
}


# --- NOMBRES DE GRUPOS DE USUARIO ---
GRUPO_EMPLEADO = 'Empleado'
GRUPO_COORDINADOR = 'Coordinador'
GRUPO_FORMACION = 'Formación'
GRUPO_RRHH = 'RRHH'
GRUPO_DIRECCION = 'Dirección'
GRUPO_ADMINISTRACION = 'Administración'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

