# Generated by Django 5.2.3 on 2025-07-04 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('formacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitopuestoformacion',
            options={'verbose_name': 'Requisito de Puesto de Formación', 'verbose_name_plural': 'Requisitos de Puestos de Formación'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='requisitopuestoformacion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='requisitopuestoformacion',
            name='obligatorio',
        ),
        migrations.RemoveField(
            model_name='requisitopuestoformacion',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='requisitopuestoformacion',
            name='periodicidad',
        ),
        migrations.RemoveField(
            model_name='requisitopuestoformacion',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='curso',
            name='es_obligatorio',
            field=models.BooleanField(default=False, help_text='Indica si este curso es generalmente obligatorio para algún puesto o perfil.'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='codigo_puesto',
            field=models.ForeignKey(blank=True, help_text='Puesto de trabajo oficial asignado a este empleado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_vinculados_requisitos', to='formacion.puestodetrabajo'),
        ),
        migrations.AddField(
            model_name='requisitopuestoformacion',
            name='fecha_implementacion',
            field=models.DateField(blank=True, help_text='Fecha a partir de la cual este requisito es efectivo.', null=True),
        ),
        migrations.AddField(
            model_name='requisitopuestoformacion',
            name='tipo_requisito',
            field=models.CharField(choices=[('obligatorio', 'Obligatorio'), ('recomendado', 'Recomendado')], default='obligatorio', help_text='Indica si el curso es obligatorio o recomendado para el puesto.', max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del curso.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('baja', 'Baja temporal/definitiva'), ('vacaciones', 'Vacaciones'), ('licencia', 'Licencia')], default='activo', help_text='Estado actual del empleado en la empresa.', max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='empleado_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(blank=True, help_text='Puesto principal del empleado.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sede',
            field=models.CharField(blank=True, choices=[('central', 'Oficina Central'), ('remoto', 'Remoto'), ('cliente', 'Oficina Cliente')], help_text='Sede principal de trabajo del empleado.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], help_text='Género del empleado.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='empleado_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='requisitopuestoformacion',
            name='curso',
            field=models.ForeignKey(help_text='Curso obligatorio o recomendado para este puesto.', on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_puesto', to='formacion.curso'),
        ),
        migrations.AlterField(
            model_name='requisitopuestoformacion',
            name='puesto',
            field=models.ForeignKey(help_text='Puesto de trabajo al que aplica este requisito de formación.', on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_formacion', to='formacion.puestodetrabajo'),
        ),
    ]
