# Generated by Django 5.2.3 on 2025-07-07 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0002_alter_requisitopuestoformacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento al que pertenece directamente el empleado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='formacion.departamento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('baja', 'Baja definitiva'), ('baja_medica', 'Baja médica'), ('vacaciones', 'Vacaciones'), ('licencia', 'Licencia')], default='activo', help_text='Estado actual del empleado en la empresa.', max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sede',
            field=models.CharField(blank=True, choices=[('tf', 'TF'), ('remoto', 'Remoto'), ('gc', 'CG')], help_text='Sede principal de trabajo del empleado.', max_length=50, null=True),
        ),
    ]
