# Generated by Django 5.2.3 on 2025-07-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0003_empleado_departamento_alter_empleado_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacion',
            name='nota_final',
            field=models.CharField(blank=True, help_text='Calificación final o estado textual (ej. Aprobado, N/A, 7.5).', max_length=100, null=True),
        ),
    ]
