# Generated by Django 5.2.3 on 2025-07-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0004_alter_participacion_nota_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titulacion',
            name='area_conocimiento',
        ),
        migrations.AddField(
            model_name='titulacion',
            name='nivel_meces',
            field=models.CharField(blank=True, choices=[('nivel_0', 'Nivel 0: Certificado de Escolaridad o equivalente'), ('nivel_1', 'Nivel 1: Técnico Superior (FP Superior, Artes Plásticas y Diseño, Deportivo)'), ('nivel_2', 'Nivel 2: Grado, Arquitecto Técnico, Ingeniero Técnico, Diplomado'), ('nivel_3', 'Nivel 3: Máster, Licenciado, Arquitecto, Ingeniero'), ('nivel_4', 'Nivel 4: Doctor'), ('otro_meces', 'Otro / No aplicable MECES')], help_text='Nivel de la titulación según el Marco Español de Cualificaciones para la Educación Superior (MECES).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='tipo_titulacion',
            field=models.CharField(choices=[('grado', 'Grado, Arquitecto Técnico, Ingeniero Técnico, Diplomado'), ('master', 'Máster, Licenciado, Arquitecto, Ingeniero'), ('doctorado', 'Doctorado'), ('fp_superior', 'Formación Profesional Grado Superior'), ('fp_medio', 'Formación Profesional Grado Medio'), ('bachiller', 'Bachillerato'), ('eso', 'Educación Secundaria Obligatoria (ESO)'), ('idioma', 'Idioma Extranjero'), ('curso_especializacion', 'Curso de Especialización/Experto'), ('otro', 'Otro')], default='otro', help_text='Tipo de cualificación académica o profesional.', max_length=50),
        ),
    ]
