# Generated by Django 5.2.3 on 2025-07-09 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0005_remove_titulacion_area_conocimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Solicitud')),
                ('titulo_curso_solicitado', models.CharField(max_length=200, verbose_name='Título del Curso Solicitado')),
                ('objetivo_curso', models.TextField(verbose_name='Objetivo del Curso')),
                ('justificacion_necesidad', models.TextField(verbose_name='Justificación de la Necesidad')),
                ('numero_participantes_estimado', models.PositiveIntegerField(help_text='Indica cuántos empleados aproximadamente necesitarían esta formación.', verbose_name='Número Estimado de Participantes')),
                ('temas_contenidos_clave', models.TextField(blank=True, help_text='Describe brevemente los principales temas o módulos que te gustaría que el curso abarcara.', null=True, verbose_name='Temas o Contenidos Clave a Cubrir')),
                ('formato_preferido', models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('online_sincrono', 'Online (con instructor en vivo)'), ('online_asincrono', 'Online (a tu ritmo)'), ('blended', 'Blended (Mixto)')], max_length=50, null=True, verbose_name='Formato Preferido')),
                ('duracion_estimada', models.CharField(blank=True, help_text='Ej: "8 horas", "2 días", "3 módulos por semana".', max_length=100, null=True, verbose_name='Duración Estimada')),
                ('fechas_horarios_preferidos', models.TextField(blank=True, help_text='Si tienes alguna preferencia de fechas o franjas horarias.', null=True, verbose_name='Fechas/Horarios Preferidos')),
                ('caracter_formacion', models.CharField(choices=[('urgente', 'Urgente / Crítico'), ('planificado', 'Para inclusión en Plan de Formación / Mejora Continua'), ('obligatorio_legal', 'Obligatorio / Legal'), ('otro', 'Otro (Especificar en Comentarios)')], default='planificado', help_text='Indica la urgencia o naturaleza de la necesidad de formación.', max_length=50, verbose_name='Carácter de la Formación')),
                ('comentarios_adicionales', models.TextField(blank=True, null=True, verbose_name='Comentarios/Notas Adicionales')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado de la Solicitud')),
                ('departamento_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formacion.departamento', verbose_name='Departamento Solicitante')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cursos', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador/a Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Curso',
                'verbose_name_plural': 'Solicitudes de Cursos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
