# Generated by Django 5.2.3 on 2025-07-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0006_solicitudcurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcurso',
            name='comentarios_procesamiento',
            field=models.TextField(blank=True, help_text='Notas internas sobre la conversión a curso formal o finalización.', null=True, verbose_name='Comentarios de Procesamiento'),
        ),
        migrations.AddField(
            model_name='solicitudcurso',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Explica por qué se ha rechazado esta solicitud.', null=True, verbose_name='Motivo del Rechazo'),
        ),
    ]
