# Generated by Django 5.2.3 on 2025-07-10 08:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0007_solicitudcurso_comentarios_procesamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacion',
            name='fecha_inicio_real',
            field=models.DateField(blank=True, help_text='Fecha de inicio asignada por RRHH para esta participación específica.', null=True),
        ),
        migrations.AlterField(
            model_name='preseleccion',
            name='curso',
            field=models.ForeignKey(help_text='Curso para el que se postularán participantes.', on_delete=django.db.models.deletion.CASCADE, related_name='preseleccionados', to='formacion.curso'),
        ),
        migrations.AlterField(
            model_name='preseleccion',
            name='prioridad',
            field=models.IntegerField(help_text='Orden de prioridad de la preselección.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='solicitudcurso',
            name='caracter_formacion',
            field=models.CharField(choices=[('urgente', 'Urgente / Crítico'), ('planificado', 'Planificado'), ('obligatorio_legal', 'Obligatorio / Legal'), ('otro', 'Otro')], default='planificado', help_text='Indica la urgencia o naturaleza de la necesidad de formación.', max_length=50, verbose_name='Carácter de la Formación'),
        ),
        migrations.AlterField(
            model_name='solicitudcurso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado de la Solicitud'),
        ),
    ]
