# Generated by Django 5.2.3 on 2025-07-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0009_encuestasatisfaccion_preguntaencuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='url',
            field=models.URLField(blank=True, help_text='URL a la que apunta la notificación (opcional).', null=True),
        ),
    ]
