# Generated by Django 5.2.3 on 2025-07-11 11:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0010_notificacion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='adquisicion_habilidades_puesto',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Excelente'), (4, 'Muy Bueno'), (3, 'Bueno'), (2, 'Regular'), (1, 'Mal')], default=3, verbose_name='He adquirido nuevas habilidades/capacidades que puedo aplicar a mi puesto de trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='conocimientos_profesor',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Excelente'), (4, 'Muy Bueno'), (3, 'Bueno'), (2, 'Regular'), (1, 'Mal')], default=3, verbose_name='Conocimientos técnicos del profesor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='empleado',
            field=models.ForeignKey(blank=True, help_text='Empleado que rellena la encuesta.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='fecha_encuesta',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='gusto_general_curso',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Excelente'), (4, 'Muy Bueno'), (3, 'Bueno'), (2, 'Regular'), (1, 'Mal')], default=3, verbose_name='En general, ¿le ha gustado el curso?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='mejora_conocimientos_carrera',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Excelente'), (4, 'Muy Bueno'), (3, 'Bueno'), (2, 'Regular'), (1, 'Mal')], default=3, verbose_name='He mejorado/ampliado conocimientos para progresar en mi carrera profesional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='nombre_curso_encuesta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='nombre_profesor_encuesta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='opinion_contenido_curso',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Excelente'), (4, 'Muy Bueno'), (3, 'Bueno'), (2, 'Regular'), (1, 'Mal')], default=3, verbose_name='Opinión sobre el contenido del curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='participacion',
            field=models.OneToOneField(blank=True, help_text='La participación a la que se refiere esta encuesta.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='formacion.participacion'),
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='sugerencias_observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Sugerencias / Observaciones'),
        ),
        migrations.RemoveField(
            model_name='encuestasatisfaccion',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='encuestasatisfaccion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='encuestasatisfaccion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='encuestasatisfaccion',
            name='titulo',
        ),
        migrations.AlterUniqueTogether(
            name='encuestasatisfaccion',
            unique_together={('participacion', 'empleado')},
        ),
    ]
