# Generated by Django 5.2.3 on 2025-07-14 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0011_alter_encuestasatisfaccion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Área a la que pertenece directamente el empleado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_directos_area', to='formacion.area'),
        ),
    ]
