# Generated by Django 5.2.3 on 2025-07-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0012_empleado_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='web',
            field=models.URLField(blank=True, help_text='Dirección URL de la página web del proveedor.', null=True),
        ),
    ]
