# Generated by Django 5.2.3 on 2025-07-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0013_proveedor_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del curso.', max_length=200),
        ),
    ]
