# Generated by Django 5.2.3 on 2025-07-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0014_alter_curso_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='titulacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Revisión RRHH'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', help_text='Estado actual de la titulación en el proceso de revisión de RRHH.', max_length=50),
        ),
        migrations.AddField(
            model_name='titulacion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Razón específica proporcionada por RRHH si la titulación fue rechazada.', null=True),
        ),
        migrations.RemoveField(
            model_name='titulacion',
            name='validado_rrhh',
        ),
    ]
