# Generated by Django 5.2.3 on 2025-07-23 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0015_alter_titulacion_unique_together_titulacion_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puestodetrabajo',
            name='area',
        ),
        migrations.AddField(
            model_name='puestodetrabajo',
            name='departamento',
            field=models.ForeignKey(default=1, help_text='Departamento al que pertenece el puesto de trabajo.', on_delete=django.db.models.deletion.CASCADE, related_name='puestos_trabajo', to='formacion.departamento'),
            preserve_default=False,
        ),
    ]
