# Generated by Django 5.2.3 on 2025-07-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0016_remove_puestodetrabajo_area_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='puestodetrabajo',
            unique_together={('nombre', 'departamento')},
        ),
    ]
