# Generated by Django 5.2.3 on 2025-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0017_alter_puestodetrabajo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestodetrabajo',
            name='nombre',
            field=models.CharField(help_text='Nombre del puesto de trabajo.', max_length=100),
        ),
    ]
